<a href="https://colab.research.google.com/github/ranjan0601/Stock_market_data_analysis/blob/main/Open_stocks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
path = '/content/drive/MyDrive/Practice_project/Call Log Top Picks (2).xlsx'

In [38]:
data = pd.read_excel(path)

In [39]:
data2 =  data.copy()

In [40]:
data2.drop("xx", axis = 1,inplace = True)

In [51]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Stock   367 non-null    object
 1   Date    367 non-null    object
 2   Reco    367 non-null    object
 3   Price   367 non-null    float64
dtypes: float64(1), object(3)
memory usage: 11.6+ KB

In [49]:
data2['Reco'] = data2['Reco'].astype("str")

In [54]:
# error: "mixed datetimes and integers in passed array"
"""pd.to_datetime() with the errors='coerce' parameter, and then check for NaT (Not a Time) values. Here's an example:"""

data2['Date'] = pd.to_datetime(data2['Date'], errors='coerce')

In [55]:
problematic_rows = data2[data2['Date'].isna()]

In [56]:
problematic_rows

                Stock Date  Reco      Price
27      Ashok Leyland  NaT  EXIT    165.400
32             Astral  NaT   BUY   1929.300
36   AU Small Finance  NaT  EXIT    745.150
65          Blue Star  NaT   BUY    762.600
68    Britannia Inds.  NaT   BUY   4955.750
69    Britannia Inds.  NaT  EXIT   4606.000
76     Cera Sanitary.  NaT   BUY   7695.750
83             CRISIL  NaT   BUY   3884.000
84   Crompton Gr. Con  NaT   BUY    402.000
91      Devyani Intl.  NaT  EXIT    193.000
100   eClerx Services  NaT   BUY   1711.200
110      Federal Bank  NaT  EXIT    124.000
125   Godrej Propert.  NaT   BUY   1420.000
133  H.G. Infra Engg.  NaT   BUY    870.250
143  HCL Technologies  NaT  EXIT   1166.900
149         HDFC Bank  NaT  EXIT   1676.250
170    Ingersoll-Rand  NaT   BUY   2860.000
181               ITC  NaT   BUY    450.600
186      Jindal Steel  NaT   BUY    420.000
189   JK Lakshmi Cem.  NaT  EXIT    419.250
191  Jubilant Ingrev.  NaT  EXIT    423.250
196    KEI Industries  NaT   BUY   2242.000
217       LTIMindtree  NaT   BUY   4060.000
219       LTIMindtree  NaT   BUY   4992.550
220       LTIMindtree  NaT  EXIT   5101.000
228            Marico  NaT  EXIT    523.450
235  Metropolis Healt  NaT   BUY   1944.000
236  Metropolis Healt  NaT  EXIT   2354.000
253      Nestle India  NaT   BUY   2285.025
257     Oberoi Realty  NaT  EXIT    986.550
269    Persistent Sys  NaT   BUY   4958.000
271     PNC Infratech  NaT  EXIT    253.000
282  Ramkrishna Forg.  NaT   BUY    467.700
302             Sobha  NaT  EXIT    531.850
304  Sona BLW Precis.  NaT  EXIT    519.750
306       Stove Kraft  NaT  EXIT    450.500
307    Suprajit Engg.  NaT   BUY    288.000
308    Suprajit Engg.  NaT  EXIT    395.350
317  Tube Investments  NaT   BUY   3336.350
322           UTI AMC  NaT   BUY    771.000
335   eClerx Services  NaT  EXIT   1702.000
337    KEI Industries  NaT  EXIT   2413.000
338    Ingersoll-Rand  NaT  EXIT   3022.000
339           UTI AMC  NaT  EXIT    760.000
340      Apollo Tyres  NaT   BUY    393.000
341        Akzo Nobel  NaT   BUY   2848.000
342     Kirloskar Oil  NaT   BUY    512.000
343      Apollo Tyres  NaT  EXIT    390.000
344               ITC  NaT  EXIT    443.000
345  Godfrey Phillips  NaT   BUY   2164.000
346       Wendt India  NaT   BUY  13114.000
363     Polycab India  NaT  EXIT   4950.000
364      Elantas Beck  NaT   BUY   8340.000
365      Elantas Beck  NaT  EXIT   8300.000
366   Praj Industries  NaT   BUY    536.000

In [42]:
data2.head()

              Stock                 Date  Reco    Price
0  Aarti Industries  2020-04-24 00:00:00   BUY   929.00
1  Aarti Industries  2020-08-13 00:00:00  EXIT  1012.25
2  Aditya Birla Cap  2018-02-01 00:00:00   BUY   174.00
3  Aditya Birla Cap  2020-03-06 00:00:00  EXIT    75.00
4      AGI Greenpac  2018-02-19 00:00:00   BUY   427.60

In [ ]:
stock_list = list(data.Stock.unique())
stock_list

In [16]:
# open_call = []

# def opencalls(df, stock_list):
#   for stock in stock_list:
#     df.order_by(by = ['Stock', 'Date'], ascending = [True, False])
#     new_df = df[df['Stock'] == stock]
#     date_list = list(new_df.Date.unique())
#     date_list = sorted(date_list, reverse = True)
#     if new_df['Reco'] == "Exit":
#       continue
#     else:
#       open_call.append(new_df.iloc())

In [46]:
def opencalls(df, stock_list):
  open_calls = []  # Assuming open_call is a list you want to append to
  for stock in stock_list:
    # Order the DataFrame by 'Stock' and 'Date'
        new_df = df[df['Stock'] == stock].sort_values(by=['Stock', 'Date'], ascending=[True, False])
        date_list = sorted(new_df.Date.unique(), reverse = True)
        subset_df = new_df[(new_df['Date'] == date_list[0]) & (~new_df['Reco'].isin(["Exit", "EXIT"]))]
        if not subset_df.empty:
           open_calls.append(subset_df.iloc[0])
        else:
          continue

  return open_calls

In [47]:
opencalls(data2, stock_list)

TypeError: 'values' is not ordered, please explicitly specify the categories order by passing in a categories argument.

In [17]:
opencalls(data2, stock_list)

AttributeError: 'list' object has no attribute 'max'